### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by william1888** [denofevil/import-cost#12]
This plugin is using a lot of CPU and almost 3GB of RAM:

![image](https://user-images.githubusercontent.com/1271688/35061764-78f0cd08-fbc2-11e7-9f99-9e3edc765e12.png)

I am running phpstorm 2017.3

**Comment by ycnmhd** [comment]
I'm having the same issue (Import Cost 1.0.7.1 running on Webstorm 2019.3)
the plugin eats ram at a constant rate
![image](https://user-images.githubusercontent.com/33285087/70397969-e9a92300-1a16-11ea-9569-1f3b4dbe7f64.png)

**Comment by anstarovoyt** [comment]
Hi! We use npm package "import-cost", so please report such performance issues there https://github.com/wix/import-cost/issues. I've fixed a couple places in the plugin, to prevent sending unrelated imports to the analyzer, but the performance in general is on their side.
