### ISSUE TITLE
How dose it calculating the size?

### ISSUE THREAD

**Issue by chenop** [denofevil/import-cost#20]
material-ui: v3.9.2
import cost: v1.0.7.1

Very interesting plugin!

Can you please explain how are calculating the size?

I compared the result with 'webpack-bundle-analyzer' and got different results.

For example:
Dialog size calculated by import cost:
![image](https://user-images.githubusercontent.com/446575/54808168-18644b00-4c88-11e9-900c-a3af7961ce2e.png)

Dialog size calculated by webpack-bundle-analyzer:
![image](https://user-images.githubusercontent.com/446575/54808306-8872d100-4c88-11e9-9872-f712f04f5391.png)

Are they calculating different things?

**Comment by buffcode** [comment]
See upstream module blog post: https://citw.dev/posts/import-cost

**Comment by anstarovoyt** [comment]
The comment is valid: we don't calculate size manually we use the external package "import-cost" for it.
