### ISSUE TITLE
Compatible build for WS-202.6397.88

### ISSUE THREAD

**Issue by ayudhDas** [denofevil/import-cost#30]
I am using the latest version of import cost plugin (1.0.74) in webstorm (version and runtime details below). The plugin in the marketplace seems to be incompatible with the current build. 

WebStorm 2020.2
Build #WS-202.6397.88, built on July 25, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep

![Screenshot 2020-08-10 at 5 59 55 PM](https://user-images.githubusercontent.com/1057084/89782653-57bc6180-db33-11ea-8c5f-070b335ac9b7.png)

**Comment by anstarovoyt** [comment]
Hi! Actually there is a compatible version but you have to uninstall the current version before installing the new version. I will try to fix it

**Comment by anstarovoyt** [comment]
fixed via 1.0.7.5
