### ISSUE TITLE
Not works in Vue components 

### ISSUE THREAD

**Issue by ONiAd** [denofevil/import-cost#31]
It isn't works in vue components or for import vue components. It would be possible implement this feature? 

Thanks for your job.

**Comment by anstarovoyt** [comment]
Hi! It works for me. Could you please provide a code sample when it doesn't work? 

<img width="483" alt="Screenshot 2020-09-08 at 16 52 03" src="https://user-images.githubusercontent.com/1753282/92485445-9eb17b80-f1f3-11ea-908c-db911dbc35e6.png">

**Comment by ONiAd** [comment]
Sorry, Now, when I was checking again it works! Thank you anyway.
