### ISSUE TITLE
Does nothing on PHPStorm 2021.2 / Typescript

### ISSUE THREAD

**Issue by buffcode** [denofevil/import-cost#42]
I would love to use this plugin, unfortunately there is no output but also no error from the plugin.
I tested multiple projects (React, NodeJS) both using Typescript.

Is there anything I can supply to debug the issues on my side?

**Comment by anstarovoyt** [comment]
Hi! Could you please create a sample project to reproduce the problem? Because it works for me in simple cases. Also, please note that the implementation runs webpack under the hood, so it can take a lot of time before showing the first result.

**Comment by anstarovoyt** [comment]
oh, I've found the problem. Please, try the new plugin version 1.0.8.212.
