### ISSUE TITLE
Does nothing on PHPStorm 2022.1

### ISSUE THREAD

**Issue by freshleafmedia** [denofevil/import-cost#47]
The plugin appears to do nothing in the latest version of PHP Storm (PS-221.5080.224)

Simple repro:

```sh
mkdir /tmp/repro
cd /tmp/repro
yarn add axios
echo -e "import axios from \"axios\";\n\naxios.get('...');" > test.js
```

![20220504-1008](https://user-images.githubusercontent.com/10062339/166652767-3c47d302-455c-4584-a438-42b2f34e64cd.png)

Is there any additional logging I can provide to help debug this?

**Comment by apuatcfbd** [comment]
yes, Its not working

**Comment by anstarovoyt** [comment]
I've found one of the possible issues. Could you please try once again with WebStorm 2022.3 (RC)?

**Comment by apudiu** [comment]
> I've found one of the possible issues. Could you please try once again with WebStorm 2022.3 (RC)?

I'm working on PHPStorm (2022.2), It's not working: https://prnt.sc/zgzw5NttF97Y

**Comment by freshleafmedia** [comment]
@anstarovoyt I can confirm this now works with WebStorm 2022.3 (RC) :tada:

However it does not work in PhpStorm 2022.3 (EAP). The plugin doesn't appear to install correctly. Clicking install shows a progress bar and shows the "Installed" state but closing and reopening the plugin window shows it as not installed.

**Comment by anstarovoyt** [comment]
it could be a bug of the IDE. Let's wait for the release candidate version of PhpStorm (I hope it will be released this week)

**Comment by anstarovoyt** [comment]
>I'm working on PHPStorm (2022.2), It's not working: https://prnt.sc/zgzw5NttF97Y

The fixes are compatible only with 2022.3 versions, unfortunatelly.

**Comment by apudiu** [comment]
When there's no issue with other plug-ins, seems like this plugin has issue with PhpStorm

**Comment by freshleafmedia** [comment]
I've just found that if you install the plugin from the Welcome screen it installs correctly and works :tada: 

![20221121-1418](https://user-images.githubusercontent.com/10062339/203077596-b7268364-30da-42d0-9dec-10ad80a6b3cb.png)

![20221121-1418_1](https://user-images.githubusercontent.com/10062339/203077700-c9d0d28e-fb93-4e90-8e2d-a2f4842a6e5c.png)

**Comment by anstarovoyt** [comment]
@freshleafmedia since you've tried the new version could you please open "Settings -> Import Cost", enable "Code Vision" and share you thoughts? I plan to enable the option by default, so far looking for the feedback.

**Comment by freshleafmedia** [comment]
Installing the plugin on PHP Storm 2022.3 RC works correctly.

**Comment by freshleafmedia** [comment]
@anstarovoyt Code vision looks good. Are there other variables available in the Presentation field?

Don't know what else there could be but didn't want to miss anything. Perhaps add a key showing the possible variables and examples could be useful?

**Comment by anstarovoyt** [comment]
No, there are no other options so fae. Thank you for the feedback!
