### ISSUE TITLE
Compatibility with 2017.3 EAP

### ISSUE THREAD

**Issue by hootlex** [denofevil/import-cost#7]
Is this plugin compatible with 2017.3 EAP?

WebStorm doesn't seem to find it while browsing repositories.

![](https://i.imgur.com/15e1Zkk.png)

When installing manually, it throws this error.
![manual installation](https://i.imgur.com/thJb257.png)

**Comment by ForsakenHarmony** [comment]
![](https://i.imgur.com/m9b7Jk7.png)

Nope, it's not compatible yet

**Comment by hootlex** [comment]
@denofevil is there a plan to support 2017.3 EAP?

**Comment by denofevil** [comment]
Just pushed a new version compatible with 2017.3

**Comment by hootlex** [comment]
Awesome, thanks for the great work 🙂
