### ISSUE TITLE
Not working on 2017.2.4

### ISSUE THREAD

**Issue by AhmadMayo** [denofevil/import-cost#8]
I've installed the plugin in a medium sized project and it's not working. I tried restarting, disabling then restarting the re-enabling then restarting, and got nothing. I don't know how to debug, so I would really appreciate if someone would help me.

**Comment by ruchern** [comment]
**PhpStorm Version:** 2017.2.4
**Import Cost version:** 1.0.3
**OS:** macOS 10.13.1 Dev Beta 2

Based on the above, it is working fine for me. Perhaps try to reinstall PhpStorm?

**Comment by AhmedSayed77** [comment]
It's WebStorm not PhpStorm. sorry I didn't mention the version
OS: ubuntu 16.04
Webstorm version: 2017.2.4
ImportCost version: 1.0.3

tried removing config files and reconfiguring, didn't work

**Comment by raienko** [comment]
macOS 10.12.6
Webstorm: 2017.2.5
Import Cost: 1.0.3

**Not working**

**Comment by mgkaradag** [comment]
macOS 10.11.6
**Webstorm: 2017.2.5**
Import Cost: 1.0.4

**Not working!**

**Comment by lsimone** [comment]
Ubuntu 17.04
**Webstorm: 2017.2.2**
Import Cost: 1.0.5

**Not working**

**Comment by anstarovoyt** [comment]
Mostlikely it is the same problem as in other issues. The plugin used an old version of import-cost package and was incompatible with new node.js version. I've fixed the problem in 2022.3, so it should work now.
